import { Layout } from "@/componets/layout";
import Providers from "@/lib/providers";
import '@gfazioli/mantine-onboarding-tour/styles.css';
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import '@mantine/core/styles.css';
import '@mantine/nprogress/styles.css';
import type { Metadata } from "next";
import React from "react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body >
        <Providers>
          <Layout>
            {children}
          </Layout>
        </Providers>

      </body>
    </html>
  );
}
